development:
  adapter: mysql2
  encoding: utf8
  database: capistrano
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock 

current:
  adapter: mysql2
  encoding: utf8
  database: capistrano
  pool: 5
  username: root
  password: capistrano
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: capistrano
  pool: 5
  username: root
  password: capistrano
  socket: /tmp/mysql.sock

